# Generated by Django 5.1.3 on 2024-11-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_alter_restaurante_criado_em_alter_restaurante_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='doacoes.restaurante'),
        ),
    ]
