# Generated by Django 5.1.3 on 2024-11-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_alter_fooddonation_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='doacoes.restaurante', verbose_name='Restaurante'),
        ),
    ]
